openapi: 3.1.0
info:
  description: ""
  title: NinjaAPI
  version: 1.0.0
servers:
- description: Production server
  url: https://api.icosa.gallery
paths:
  /v1/assets/{asset}:
    get:
      operationId: icosa_api_assets_get_asset
      parameters:
      - explode: false
        in: path
        name: asset
        required: true
        schema:
          title: Asset
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetSchema'
          description: OK
      summary: Get Asset
      tags:
      - Assets
  /v1/assets:
    get:
      operationId: icosa_api_assets_get_assets
      parameters:
      - example: ANIMALS
        explode: true
        in: query
        name: category
        required: false
        schema:
          $ref: '#/components/schemas/Category'
        style: form
      - explode: true
        in: query
        name: curated
        required: false
        schema:
          default: false
          title: Curated
          type: boolean
        style: form
      - description: Filter by format
        explode: true
        in: query
        name: format
        required: false
        schema:
          items:
            $ref: '#/components/schemas/FormatFilter'
          nullable: true
          type: array
        style: form
      - explode: true
        in: query
        name: keywords
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: name
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: description
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: tag
        required: false
        schema:
          items:
            nullable: true
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: orderBy
        required: false
        schema:
          $ref: '#/components/schemas/Order'
        style: form
      - explode: true
        in: query
        name: maxComplexity
        required: false
        schema:
          $ref: '#/components/schemas/Complexity'
        style: form
      - explode: true
        in: query
        name: triangleCountMin
        required: false
        schema:
          nullable: true
          type: integer
        style: form
      - explode: true
        in: query
        name: triangleCountMax
        required: false
        schema:
          nullable: true
          type: integer
        style: form
      - explode: true
        in: query
        name: zipArchiveUrl
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: authorName
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: license
        required: false
        schema:
          $ref: '#/components/schemas/LicenseFilter'
        style: form
      - explode: true
        in: query
        name: pageToken
        required: false
        schema:
          title: Pagetoken
          type: string
        style: form
      - explode: true
        in: query
        name: pageSize
        required: false
        schema:
          title: Pagesize
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedAssetSchema'
          description: OK
      summary: Get Assets
      tags:
      - Assets
  /v1/login/device_login:
    post:
      operationId: icosa_api_login_device_login
      parameters:
      - explode: true
        in: query
        name: device_code
        required: true
        schema:
          title: Device Code
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginToken'
          description: OK
      summary: Device Login
      tags:
      - Login
  /v1/oembed:
    get:
      operationId: icosa_api_oembed_oembed
      parameters:
      - explode: true
        in: query
        name: url
        required: false
        schema:
          title: Url
          type: string
        style: form
      - explode: true
        in: query
        name: format
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: maxwidth
        required: false
        schema:
          nullable: true
          type: integer
        style: form
      - explode: true
        in: query
        name: maxheight
        required: false
        schema:
          nullable: true
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OembedOut'
          description: OK
      summary: Oembed
      tags:
      - Oembed
  /v1/users/me:
    get:
      operationId: icosa_api_users_get_users_me
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUserSchema'
          description: OK
      security:
      - JWTAuth: []
      summary: Get Users Me
      tags:
      - Users
    patch:
      operationId: icosa_api_users_update_user
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchUserSchema'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUserSchema'
          description: OK
      security:
      - JWTAuth: []
      summary: Update User
      tags:
      - Users
  /v1/users/me/assets:
    get:
      operationId: icosa_api_users_get_me_assets
      parameters:
      - example: ANIMALS
        explode: true
        in: query
        name: category
        required: false
        schema:
          $ref: '#/components/schemas/Category'
        style: form
      - explode: true
        in: query
        name: curated
        required: false
        schema:
          default: false
          title: Curated
          type: boolean
        style: form
      - description: Filter by format
        explode: true
        in: query
        name: format
        required: false
        schema:
          items:
            $ref: '#/components/schemas/FormatFilter'
          nullable: true
          type: array
        style: form
      - explode: true
        in: query
        name: keywords
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: name
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: description
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: tag
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: orderBy
        required: false
        schema:
          $ref: '#/components/schemas/Order'
        style: form
      - explode: true
        in: query
        name: maxComplexity
        required: false
        schema:
          $ref: '#/components/schemas/Complexity'
        style: form
      - explode: true
        in: query
        name: triangleCountMin
        required: false
        schema:
          nullable: true
          type: integer
        style: form
      - explode: true
        in: query
        name: triangleCountMax
        required: false
        schema:
          nullable: true
          type: integer
        style: form
      - explode: true
        in: query
        name: zipArchiveUrl
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: visibility
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: pageToken
        required: false
        schema:
          title: Pagetoken
          type: string
        style: form
      - explode: true
        in: query
        name: pageSize
        required: false
        schema:
          title: Pagesize
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedAssetSchema'
          description: OK
      security:
      - JWTAuth: []
      summary: Get Me Assets
      tags:
      - Users
  /v1/users/me/assets/{asset}:
    delete:
      operationId: icosa_api_users_delete_asset
      parameters:
      - explode: false
        in: path
        name: asset
        required: true
        schema:
          title: Asset
          type: string
        style: simple
      responses:
        "204":
          content:
            application/json:
              schema:
                title: Response
                type: integer
          description: No Content
      security:
      - JWTAuth: []
      summary: Delete Asset
      tags:
      - Users
    get:
      operationId: icosa_api_users_get_me_asset
      parameters:
      - explode: false
        in: path
        name: asset
        required: true
        schema:
          title: Asset
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetSchema'
          description: OK
      security:
      - JWTAuth: []
      summary: Get Me Asset
      tags:
      - Users
  /v1/users/me/likedassets:
    get:
      operationId: icosa_api_users_get_me_likedassets
      parameters:
      - example: ANIMALS
        explode: true
        in: query
        name: category
        required: false
        schema:
          $ref: '#/components/schemas/Category'
        style: form
      - explode: true
        in: query
        name: curated
        required: false
        schema:
          default: false
          title: Curated
          type: boolean
        style: form
      - description: Filter by format
        explode: true
        in: query
        name: format
        required: false
        schema:
          items:
            $ref: '#/components/schemas/FormatFilter'
          nullable: true
          type: array
        style: form
      - explode: true
        in: query
        name: keywords
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: name
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: description
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: tag
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: orderBy
        required: false
        schema:
          $ref: '#/components/schemas/Order'
        style: form
      - explode: true
        in: query
        name: maxComplexity
        required: false
        schema:
          $ref: '#/components/schemas/Complexity'
        style: form
      - explode: true
        in: query
        name: triangleCountMin
        required: false
        schema:
          nullable: true
          type: integer
        style: form
      - explode: true
        in: query
        name: triangleCountMax
        required: false
        schema:
          nullable: true
          type: integer
        style: form
      - explode: true
        in: query
        name: zipArchiveUrl
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: authorName
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: license
        required: false
        schema:
          $ref: '#/components/schemas/LicenseFilter'
        style: form
      - explode: true
        in: query
        name: pageToken
        required: false
        schema:
          title: Pagetoken
          type: string
        style: form
      - explode: true
        in: query
        name: pageSize
        required: false
        schema:
          title: Pagesize
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedAssetSchema'
          description: OK
      security:
      - JWTAuth: []
      summary: Get Me Likedassets
      tags:
      - Users
components:
  schemas:
    AssetFormat:
      example:
        role: role
        formatComplexity:
          lodHint: 6
          triangleCount: 0
        root:
          relativePath: relativePath
          contentType: contentType
          url: url
        resources:
        - relativePath: relativePath
          contentType: contentType
          url: url
        - relativePath: relativePath
          contentType: contentType
          url: url
        formatType: formatType
        zip_archive_url: zip_archive_url
      properties:
        root:
          $ref: '#/components/schemas/AssetResource'
        resources:
          items:
            $ref: '#/components/schemas/AssetResource'
          nullable: true
          type: array
        formatComplexity:
          $ref: '#/components/schemas/FormatComplexity'
        formatType:
          title: Formattype
          type: string
        zip_archive_url:
          nullable: true
          type: string
        role:
          nullable: true
          type: string
      required:
      - formatComplexity
      title: AssetFormat
    AssetResource:
      example:
        relativePath: relativePath
        contentType: contentType
        url: url
      properties:
        relativePath:
          title: Relativepath
          type: string
        contentType:
          title: Contenttype
          type: string
        url:
          title: Url
          type: string
      required:
      - contentType
      - relativePath
      - url
      title: AssetResource
    AssetSchema:
      example:
        presentationParams: "{}"
        thumbnail:
          relativePath: relativePath
          contentType: contentType
          url: url
        formats:
        - role: role
          formatComplexity:
            lodHint: 6
            triangleCount: 0
          root:
            relativePath: relativePath
            contentType: contentType
            url: url
          resources:
          - relativePath: relativePath
            contentType: contentType
            url: url
          - relativePath: relativePath
            contentType: contentType
            url: url
          formatType: formatType
          zip_archive_url: zip_archive_url
        - role: role
          formatComplexity:
            lodHint: 6
            triangleCount: 0
          root:
            relativePath: relativePath
            contentType: contentType
            url: url
          resources:
          - relativePath: relativePath
            contentType: contentType
            url: url
          - relativePath: relativePath
            contentType: contentType
            url: url
          formatType: formatType
          zip_archive_url: zip_archive_url
        visibility: visibility
        displayName: displayName
        description: description
        updateTime: 2000-01-23T04:56:07.000+00:00
        authorId: authorId
        url: url
        tags:
        - tags
        - tags
        license: license
        createTime: 2000-01-23T04:56:07.000+00:00
        authorName: authorName
        assetId: assetId
        name: name
        licenseVersion: licenseVersion
        triangleCount: 1
        isCurated: true
      properties:
        authorId:
          title: Authorid
          type: string
        authorName:
          title: Authorname
          type: string
        name:
          title: Name
          type: string
        description:
          nullable: true
          type: string
        createTime:
          format: date-time
          title: Createtime
          type: string
        updateTime:
          format: date-time
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        assetId:
          title: Assetid
          type: string
        formats:
          items:
            $ref: '#/components/schemas/AssetFormat'
          type: array
        displayName:
          nullable: true
          type: string
        visibility:
          title: Visibility
          type: string
        tags:
          default: []
          items:
            type: string
          type: array
        isCurated:
          nullable: true
          type: boolean
        thumbnail:
          $ref: '#/components/schemas/Thumbnail'
        triangleCount:
          title: Trianglecount
          type: integer
        presentationParams:
          nullable: true
          type: object
        license:
          title: License
          type: string
        licenseVersion:
          nullable: true
          type: string
      required:
      - assetId
      - authorName
      - createTime
      - description
      - displayName
      - formats
      - license
      - licenseVersion
      - name
      - thumbnail
      - triangleCount
      - updateTime
      - url
      - visibility
      title: AssetSchema
    FormatComplexity:
      example:
        lodHint: 6
        triangleCount: 0
      properties:
        triangleCount:
          nullable: true
          type: integer
        lodHint:
          nullable: true
          type: integer
      title: FormatComplexity
    Thumbnail:
      example:
        relativePath: relativePath
        contentType: contentType
        url: url
      properties:
        relativePath:
          nullable: true
          type: string
        contentType:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
      title: Thumbnail
    AssetFilters:
      properties:
        category:
          $ref: '#/components/schemas/Category'
        curated:
          default: false
          title: Curated
          type: boolean
        format:
          items:
            $ref: '#/components/schemas/FormatFilter'
          nullable: true
          type: array
        keywords:
          nullable: true
          type: string
        name:
          nullable: true
          type: string
        description:
          nullable: true
          type: string
        tag:
          items:
            type: string
          type: array
        orderBy:
          $ref: '#/components/schemas/Order'
        maxComplexity:
          $ref: '#/components/schemas/Complexity'
        triangleCountMin:
          nullable: true
          type: integer
        triangleCountMax:
          nullable: true
          type: integer
        zipArchiveUrl:
          nullable: true
          type: string
        authorName:
          nullable: true
          type: string
        license:
          $ref: '#/components/schemas/LicenseFilter'
      title: AssetFilters
    Category:
      enum:
      - MISCELLANEOUS
      - ANIMALS
      - ARCHITECTURE
      - ART
      - CULTURE
      - EVENTS
      - FOOD
      - HISTORY
      - HOME
      - NATURE
      - OBJECTS
      - PEOPLE
      - PLACES
      - SCIENCE
      - SPORTS
      - TECH
      - TRANSPORT
      - TRAVEL
      title: Category
      type: string
    Complexity:
      enum:
      - COMPLEX
      - MEDIUM
      - SIMPLE
      title: Complexity
      type: string
    FormatFilter:
      enum:
      - TILT
      - BLOCKS
      - GLTF
      - GLTF1
      - GLTF2
      - OBJ
      - FBX
      - -TILT
      - -BLOCKS
      - -GLTF
      - -GLTF1
      - -GLTF2
      - -OBJ
      - -FBX
      title: FormatFilter
      type: string
    Input:
      properties:
        pageToken:
          title: Pagetoken
          type: string
        pageSize:
          title: Pagesize
          type: string
      title: Input
    LicenseFilter:
      enum:
      - REMIXABLE
      - ALL_CC
      - CREATIVE_COMMONS_BY_3_0
      - CREATIVE_COMMONS_BY_ND_3_0
      - CREATIVE_COMMONS_BY_4_0
      - CREATIVE_COMMONS_BY_ND_4_0
      - CREATIVE_COMMONS_BY
      - CREATIVE_COMMONS_BY_ND
      - CREATIVE_COMMONS_0
      title: LicenseFilter
      type: string
    Order:
      enum:
      - NEWEST
      - OLDEST
      - BEST
      - CREATE_TIME
      - -CREATE_TIME
      - UPDATE_TIME
      - -UPDATE_TIME
      - TRIANGLE_COUNT
      - -TRIANGLE_COUNT
      - LIKED_TIME
      - -LIKED_TIME
      - LIKES
      - -LIKES
      - DOWNLOADS
      - -DOWNLOADS
      - DISPLAY_NAME
      - -DISPLAY_NAME
      - AUTHOR_NAME
      - -AUTHOR_NAME
      title: Order
      type: string
    PagedAssetSchema:
      example:
        assets:
        - presentationParams: "{}"
          thumbnail:
            relativePath: relativePath
            contentType: contentType
            url: url
          formats:
          - role: role
            formatComplexity:
              lodHint: 6
              triangleCount: 0
            root:
              relativePath: relativePath
              contentType: contentType
              url: url
            resources:
            - relativePath: relativePath
              contentType: contentType
              url: url
            - relativePath: relativePath
              contentType: contentType
              url: url
            formatType: formatType
            zip_archive_url: zip_archive_url
          - role: role
            formatComplexity:
              lodHint: 6
              triangleCount: 0
            root:
              relativePath: relativePath
              contentType: contentType
              url: url
            resources:
            - relativePath: relativePath
              contentType: contentType
              url: url
            - relativePath: relativePath
              contentType: contentType
              url: url
            formatType: formatType
            zip_archive_url: zip_archive_url
          visibility: visibility
          displayName: displayName
          description: description
          updateTime: 2000-01-23T04:56:07.000+00:00
          authorId: authorId
          url: url
          tags:
          - tags
          - tags
          license: license
          createTime: 2000-01-23T04:56:07.000+00:00
          authorName: authorName
          assetId: assetId
          name: name
          licenseVersion: licenseVersion
          triangleCount: 1
          isCurated: true
        - presentationParams: "{}"
          thumbnail:
            relativePath: relativePath
            contentType: contentType
            url: url
          formats:
          - role: role
            formatComplexity:
              lodHint: 6
              triangleCount: 0
            root:
              relativePath: relativePath
              contentType: contentType
              url: url
            resources:
            - relativePath: relativePath
              contentType: contentType
              url: url
            - relativePath: relativePath
              contentType: contentType
              url: url
            formatType: formatType
            zip_archive_url: zip_archive_url
          - role: role
            formatComplexity:
              lodHint: 6
              triangleCount: 0
            root:
              relativePath: relativePath
              contentType: contentType
              url: url
            resources:
            - relativePath: relativePath
              contentType: contentType
              url: url
            - relativePath: relativePath
              contentType: contentType
              url: url
            formatType: formatType
            zip_archive_url: zip_archive_url
          visibility: visibility
          displayName: displayName
          description: description
          updateTime: 2000-01-23T04:56:07.000+00:00
          authorId: authorId
          url: url
          tags:
          - tags
          - tags
          license: license
          createTime: 2000-01-23T04:56:07.000+00:00
          authorName: authorName
          assetId: assetId
          name: name
          licenseVersion: licenseVersion
          triangleCount: 1
          isCurated: true
        totalSize: 0
        nextPageToken: nextPageToken
      properties:
        assets:
          items:
            $ref: '#/components/schemas/AssetSchema'
          type: array
        totalSize:
          title: Totalsize
          type: integer
        nextPageToken:
          nullable: true
          type: string
      required:
      - assets
      - totalSize
      title: PagedAssetSchema
    LoginToken:
      example:
        access_token: access_token
        token_type: token_type
      properties:
        access_token:
          title: Access Token
          type: string
        token_type:
          title: Token Type
          type: string
      required:
      - access_token
      - token_type
      title: LoginToken
    OembedOut:
      example:
        author_name: author_name
        cache_age: cache_age
        provider_url: provider_url
        type: rich
        title: title
        thumbnail_url: thumbnail_url
        version: "1.0"
        thumbnail_height: thumbnail_height
        author_url: author_url
        thumbnail_width: thumbnail_width
        width: 0
        html: html
        provider_name: provider_name
        height: 6
      properties:
        type:
          enum:
          - rich
          title: Type
          type: string
        version:
          enum:
          - "1.0"
          title: Version
          type: string
        title:
          nullable: true
          type: string
        author_name:
          nullable: true
          type: string
        author_url:
          nullable: true
          type: string
        provider_name:
          nullable: true
          type: string
        provider_url:
          nullable: true
          type: string
        cache_age:
          nullable: true
          type: string
        thumbnail_url:
          nullable: true
          type: string
        thumbnail_width:
          nullable: true
          type: string
        thumbnail_height:
          nullable: true
          type: string
        html:
          title: Html
          type: string
        width:
          title: Width
          type: integer
        height:
          title: Height
          type: integer
      required:
      - height
      - html
      - type
      - version
      - width
      title: OembedOut
    FullUserSchema:
      example:
        displayName: displayName
        description: description
        id: 0
        email: email
        url: url
        username: username
      properties:
        id:
          title: Id
          type: integer
        username:
          title: Username
          type: string
        email:
          format: email
          title: Email
          type: string
        displayName:
          title: Displayname
          type: string
        description:
          nullable: true
          type: string
        url:
          title: Url
          type: string
      required:
      - email
      - id
      - url
      - username
      title: FullUserSchema
    PatchUserSchema:
      example:
        displayname: displayname
        description: description
        email: email
      properties:
        email:
          format: email
          nullable: true
          type: string
        displayname:
          title: Displayname
          type: string
        description:
          nullable: true
          type: string
      title: PatchUserSchema
    UserAssetFilters:
      properties:
        category:
          $ref: '#/components/schemas/Category'
        curated:
          default: false
          title: Curated
          type: boolean
        format:
          items:
            $ref: '#/components/schemas/FormatFilter'
          nullable: true
          type: array
        keywords:
          nullable: true
          type: string
        name:
          nullable: true
          type: string
        description:
          nullable: true
          type: string
        tag:
          items:
            type: string
          type: array
        orderBy:
          $ref: '#/components/schemas/Order'
        maxComplexity:
          $ref: '#/components/schemas/Complexity'
        triangleCountMin:
          nullable: true
          type: integer
        triangleCountMax:
          nullable: true
          type: integer
        zipArchiveUrl:
          nullable: true
          type: string
        visibility:
          nullable: true
          type: string
      title: UserAssetFilters
  securitySchemes:
    JWTAuth:
      scheme: bearer
      type: http

